### PR TITLE
Add Favicon Support and Remove Unnecessary Support Codes Which Can Be Edited Through Customizer

### PR DESCRIPTION
**Pull request by manishsuwal**
Independent Publisher doesn't have favicon support, so I thought of adding it on the Child theme. 

We can Enable 'Multi-Author Mode', and hide 'Post Word Count' through the Customizer. So, I've removed those support codes. 

I've also removed trailing spaces from the README.md file.

### CODE REVIEW

**Comment by raamdev** [comment]
Great work! Thank you, Manish. Maybe I should add Favicon support directly to the theme? What do you think?

**Comment by manishsuwal** [comment]
I once thought favicon support should be left to plugin, but I think that's not the right approach now. It's because favicon isn't too heavy. 

So, I guess the better approach now would be to keep it in the theme. 

I want to keep the favicon support in the Customizer just like how we keep header image. But sadly, I don't know how to do it. 

screen shot 2014-02-27 at 7 02 23 pm

**Comment by raamdev** [comment]
I agree.

Does Header Image show up in the Customizer for you? It's not there for me.

**Comment by manishsuwal** [comment]
It shows up on mine. The screenshot above is from my website. You can check
it by going to my site.

I would love to create that for favicon as well.

**Comment by raamdev** [comment]
That's really strange. It doesn't show up on my system in the Customizer. I was trying to debug it for the longest time and I eventually gave up because I couldn't figure out why it wasn't showing in the Customizer for me. I did everything correctly in the code, but it refused to show there.

It's good to know that it's actually working the way it's supposed to! :)

Anyway, I've created a feature request for this and I'll work on it soon:
https://github.com/raamdev/independent-publisher/issues/61

**Comment by manishsuwal** [comment]
It shows on mine, but doesn't show properly. The real header is round, but in the customizer it's rectangle, and the photo also stretches. 

I think it would be great if we can make the customizer header image round like how it shows in the website. If it's not possible, then at least we should try and not stretch it.

**Comment by raamdev** [comment]
It's not possible due to the way the customizer controls work. The header image is round on the site because it uses border radius in the CSS. The round header image on the site is intentional, because it keeps the style consistent with the rest of the site (e.g., all the comment author avatars have round images). 

If you want to remove the styling from your header image, you can add the following CSS to a child theme:

``` css
.site-logo img {
    border-radius: 0 !important;
    -webkit-border-radius: 0 !important;
    -moz-border-radius: 0 !important;
    border-radius: 0 !important;
    max-width: 100% !important;
}
```

**Comment by manishsuwal** [comment]
> The header image is round on the site because it uses border radius in the CSS. The round header image on the site is intentional, because it keeps the style consistent with the rest of the site (e.g., all the comment author avatars have round images).

I agree, and I really love the round header. 

> If you want to remove the styling from your header image, you can add the following CSS to a child theme:

I don't want to remove styling from my header. 

What I meant is that the header image in Customizer stretches. Is it normal? Look at the screenshot below: 
screen shot 2014-02-27 at 10 13 57 pm

**Comment by raamdev** [comment]
Yes, I believe that's normal. It's just stretching it to fit the width of the control. Does the same thing happen if you upload a rectangle image (not a square image like your ENWIL logo)?

**Comment by raamdev** [comment]
Also, note that the Header image control and uploader are part of WordPress Core, not this theme. So if there's an issue with the control, you should probably post it on [WordPress Trac](http://trac.wordpress.org), not here. :)

**Comment by manishsuwal** [comment]
Oh yes. I totally forgot about that.

**Pull request merged**
